### ISSUE TITLE
Choose whether or not to keep files on export as well as delete them or not on import

### ISSUE THREAD

**Issue by sorrentinov** [bsorrentino/zx-powerapps-cli#3]
Should be useful to have:

1. an option to interactively ask if you want keep "managed" and "unmanaged" files on zx-export-solution 
2. an option to interactively ask if you want delete "managed" and "unmanaged" files on zx-import-solution 

The first option could be useful if you need to use that files in a DevOps pipeline

**Comment by bsorrentino** [comment]
Hi @sorrentinov thanks for feedback

I've intentionally delete the `.zip` because this cli is essentially thought for interactive use but anyway this feature looks interesting 

However if you're tackling with Azure Devops Pipeline take a look to [Microsoft Power Platform Build Tools for Azure DevOps](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools) I've used it and it is pretty straightforward

**Comment by bsorrentino** [comment]
Hi @sorrentinov 

I've released version `1.5.3` adding support of `--keepzip` command line argument only for export solution use case

Again, this cli currently is not ready to be used in pipeline, its goal is to implement common workflow useful for interactive and local usage
